apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-cb-service-search-engine
  namespace: cb-micro-services
  labels:
    app: cb-service-search-engine
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cb-service-search-engine
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cb-service-search-engine
    spec:
      containers:
      - name: cb-service-search-engine
        image: 037742176437.dkr.ecr.us-east-1.amazonaws.com/cb_service_search_engine_staging:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1000m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 4000Mi
        ports:
          - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthcheck/
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /healthcheck/
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 60