apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment- #CHANGE_ME
  namespace: cb-micro-services #CHANGE_ME <cb-micro-services | cb-backends>
  labels:
    app: cb-service-search-engine #CHANGE_ME
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cb-service-search-engine #CHANGE_ME
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cb-service-search-engine #CHANGE_ME
    spec:
      containers:
      - name: cb-service-search-engine #CHANGE_ME
        image: 037742176437.dkr.ecr.us-east-1.amazonaws.com/ #CHANGE_ME:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1000m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 4000Mi
        ports:
          - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthcheck/
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /healthcheck/
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 60