---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: service- #CHANGE_ME
  namespace: cb-micro-services #CHANGE_ME <cb-micro-services | cb-backends>
spec:
  scaleTargetRef:
    kind: Deployment
    name: deployment- #CHANGE_ME
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 40