---
apiVersion: v1
kind: Service
metadata:
  namespace: cb-micro-services
  name: cb-service-search-engine
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-name: "k8s-priv-staging-serv-search"
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: ClusterIP
  selector:
    app.kubernetes.io/name: cb-service-search-engine
---