name: Build to Amazon ECR
# Controls when the action will run.
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      RELEASE_REVISION:
        required: true
        type: string

env:
  ECR_REGISTRY: 037742176437.dkr.ecr.us-east-1.amazonaws.com
  SLACK_ICON: "[icon URL]"
  SLACK_COLOR: '#228B22'
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  MSG_MINIMAL: false
  SLACK_CHANNEL: github-actions
  SLACK_USERNAME: 'Dobby'
  SLACK_FOOTER: 'Powered by the House of the Elf'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ecr:
    name: Build ECR
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Slack notification Begin
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: 'Deployment :rocket:'
          SLACK_MESSAGE: "Excuse me Master \n I will begin the building of ${{github.repository}} \n Branch to deploy -> ${{github.ref}} \n Iniciated by ${{github.actor}}"

      - name: Obtain GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          GITHUB_TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$GITHUB_TOKEN"
          echo "::set-output name=token::$GITHUB_TOKEN"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Docker cache layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Slack notification Buildx
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Deployment Buildx :ok_hand:'
          SLACK_MESSAGE: "Everything looks good on your code Master ${{inputs.ECR_REPOSITORY}} :ok_hand: \n Branch to deploy -> ${{github.ref}} \n Starting the building and push"

      - name: Build & Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          RELEASE_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.RELEASE_REVISION }}
          RELEASE_IMAGE_LATEST: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:latest
        run: |
          echo "ENVIRONMENT -> ${{ inputs.ENVIRONMENT }}"
          docker buildx create --use
          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new --build-arg INPUT_LOGDNA_INGESTION_KEY=${{ secrets.LOGDNA_INGESTION_KEY }} --build-arg INPUT_ENVIRONMENT=${{ inputs.ENVIRONMENT }} --build-arg INPUT_GITHUB_TOKEN=${{ steps.GithubAppAuth.outputs.token }} --build-arg INPUT_AWS_ACCESS=${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg INPUT_AWS_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --build-arg INPUT_AWS_REGION=${{ secrets.AWS_REGION }} -t ${{ env.RELEASE_IMAGE }} -t ${{ env.RELEASE_IMAGE_LATEST }} --push .
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Slack notification Deployment
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: 'Deployment to ECR :sparkles:'
          SLACK_MESSAGE: "Excuse me Master ${{github.actor}} \n I Push your docker \n Repository ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:latest \n Branch to deploy -> ${{github.ref}}"

      - name: Slack ERROR
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: 'ACTION Error :boom:'
          SLACK_MESSAGE: "Excuse me Master ${{github.actor}} \n I fail the action ${{ inputs.ECR_REPOSITORY }}/${{ inputs.ENVIRONMENT }} \n BAD BAD Dobby"
          SLACK_COLOR: ${{ job.status }}

      - name: Slack ErrorGif
        if: ${{ failure() }}
        uses: archive/github-actions-slack@v2.0.0
        id: notify-bad
        with:
          slack-optional-as_user: false
          slack-optional-username: Dobby
          slack-bot-user-oauth-access-token: ${{ secrets.BOT_SLACK_TOKEN }}
          slack-channel: ${{ secrets.BOT_SLACK_CHANNEL }}
          slack-text: https://i.gifer.com/INdX.gif

      - name: Slack Wiii
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: ':tada:'
          SLACK_MESSAGE: "Excuse me Master ${{github.actor}} \n I finish the building of ${{inputs.ECR_REPOSITORY}}/${{ inputs.ENVIRONMENT }} for you \n I will try to deploy it for you"
          SLACK_COLOR: ${{ job.status }}

      - name: Slack Wiiii
        if: ${{ success() }}
        uses: archive/github-actions-slack@v2.0.0
        id: notify-wiii
        with:
          slack-optional-as_user: false
          slack-optional-username: Dobby
          slack-bot-user-oauth-access-token: ${{ secrets.BOT_SLACK_TOKEN }}
          slack-channel: ${{ secrets.BOT_SLACK_CHANNEL }}
          slack-text: https://i.gifer.com/7Oi8.gif

      - name: Slack Cancel
        if: ${{ cancelled() }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: ':boom:'
          SLACK_MESSAGE: "Excuse me Master ${{github.actor}} \n you cancel my action on ${{inputs.ECR_REPOSITORY}}/${{ inputs.ENVIRONMENT }} \n DOBBY do something wrong??"
          SLACK_COLOR: ${{ job.status }}
          
      - name: Slack CancelGif
        if: ${{ cancelled() }}
        uses: archive/github-actions-slack@v2.0.0
        id: notify-canceled
        with:
          slack-optional-as_user: false
          slack-optional-username: Dobby
          slack-bot-user-oauth-access-token: ${{ secrets.BOT_SLACK_TOKEN }}
          slack-channel: ${{ secrets.BOT_SLACK_CHANNEL }}
          slack-text: https://i.gifer.com/LHtI.gif