name: Deploy to Amazon EKS v2
on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  SLACK_ICON: "[icon URL]"
  SLACK_COLOR: '#228B22'
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  MSG_MINIMAL: false
  SLACK_CHANNEL: github-actions
  SLACK_USERNAME: 'Dobby'
  SLACK_FOOTER: ''

jobs:
  define-vars:
    name: Define Deploy Vars
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: xoxb-539737845650-3862939171476-uBM6b6Bir45RCgJxcr7ihfRf
          slack-channel: C02E4CWPDQR
          slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}" 🤓
      - name: Slack notification Begin
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Deployment :rocket:'
          SLACK_MESSAGE: "https://i.gifer.com/7Oi3.gif"
